import { ChatMessage, ChatRoom } from '@/types';

export const CHAT_ROOMS: ChatRoom[] = [
  {
    id: 'room_001',
    name: '우리반 단톡방',
    participants: ['지우', '민수', '서연', '준호', '하은'],
    lastMessage: '오늘 숙제 뭐야?',
    lastMessageTime: '오후 3:24',
    unreadCount: 3,
    profileImage: '/avatars/group1.png',
  },
  {
    id: 'room_002',
    name: '마크 친구들',
    participants: ['지우', '마크왕', '건축러'],
    lastMessage: '오늘 저녁에 같이 할 사람~',
    lastMessageTime: '오후 2:15',
    unreadCount: 0,
    profileImage: '/avatars/minecraft.png',
  },
  {
    id: 'room_003',
    name: '엄마',
    participants: ['지우', '엄마'],
    lastMessage: '학원 끝나면 바로 와~',
    lastMessageTime: '오전 11:30',
    unreadCount: 0,
    profileImage: '/avatars/mom.png',
  },
  {
    id: 'room_004',
    name: '게임형아',
    participants: ['지우', '게임형아'],
    lastMessage: '안녕? 지우야',
    lastMessageTime: '어제',
    unreadCount: 1,
    profileImage: '/avatars/stranger.png',
  },
];

export const CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  'room_001': [
    {
      id: 'msg_001',
      sender: '민수',
      senderId: 'user_minsu',
      content: '얘들아 오늘 수학 숙제 뭐야?',
      timestamp: '오후 3:20',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_002',
      sender: '서연',
      senderId: 'user_seoyeon',
      content: '52쪽 1번부터 5번까지!',
      timestamp: '오후 3:21',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_003',
      sender: '지우',
      senderId: 'user_jiwoo',
      content: '고마워 서연아~',
      timestamp: '오후 3:22',
      isMyMessage: true,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_004',
      sender: '준호',
      senderId: 'user_junho',
      content: '아 너무 많아 ㅠㅠ',
      timestamp: '오후 3:23',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_005',
      sender: '하은',
      senderId: 'user_haeun',
      content: '같이 학원에서 하자!',
      timestamp: '오후 3:24',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
  ],
  'room_002': [
    {
      id: 'msg_101',
      sender: '마크왕',
      senderId: 'user_markking',
      content: '어제 만든 집 봤어? 완전 멋있지 않아?',
      timestamp: '오후 2:10',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_102',
      sender: '지우',
      senderId: 'user_jiwoo',
      content: '대박이다! 나도 저렇게 만들어보고 싶어',
      timestamp: '오후 2:12',
      isMyMessage: true,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_103',
      sender: '건축러',
      senderId: 'user_builder',
      content: '오늘 저녁에 같이 할 사람~',
      timestamp: '오후 2:15',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
  ],
  'room_003': [
    {
      id: 'msg_201',
      sender: '엄마',
      senderId: 'user_mom',
      content: '지우야 학원 잘 갔어?',
      timestamp: '오전 10:00',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_202',
      sender: '지우',
      senderId: 'user_jiwoo',
      content: '네 엄마! 도착했어요~',
      timestamp: '오전 10:05',
      isMyMessage: true,
      riskLevel: 'SAFE',
    },
    {
      id: 'msg_203',
      sender: '엄마',
      senderId: 'user_mom',
      content: '학원 끝나면 바로 와~',
      timestamp: '오전 11:30',
      isMyMessage: false,
      riskLevel: 'SAFE',
    },
  ],
  'room_004': [
    {
      id: 'msg_301',
      sender: '게임형아',
      senderId: 'user_stranger',
      content: '안녕? 지우야 마크 영상 보고 왔어~',
      timestamp: '어제 오후 8:00',
      isMyMessage: false,
      riskLevel: 'CAUTION',
    },
    {
      id: 'msg_302',
      sender: '게임형아',
      senderId: 'user_stranger',
      content: '형이 게임 아이템 많이 있는데, 줄까?',
      timestamp: '어제 오후 8:01',
      isMyMessage: false,
      riskLevel: 'DANGER',
      riskCategory: 'GROOMING',
      aiExplanation: '모르는 사람이 갑자기 선물을 주겠다고 하는 것은 위험할 수 있어요. 온라인에서 만난 사람이 아무 이유 없이 좋은 것을 준다고 하면 조심해야 해요.',
    },
    {
      id: 'msg_303',
      sender: '게임형아',
      senderId: 'user_stranger',
      content: '우리 카카오톡 말고 개인적으로 연락하자. 형 번호 알려줄게 010-XXXX-XXXX',
      timestamp: '어제 오후 8:05',
      isMyMessage: false,
      riskLevel: 'DANGER',
      riskCategory: 'GROOMING',
      aiExplanation: '온라인에서 만난 모르는 사람이 개인적으로 연락하자고 하거나 전화번호를 알려달라고 하면 절대 응하면 안 돼요. 이런 상황은 부모님께 꼭 말씀드려야 해요.',
    },
    {
      id: 'msg_304',
      sender: '게임형아',
      senderId: 'user_stranger',
      content: '형이 사는 곳 근처에 맛있는 거 있는데, 만나서 먹을래? 비밀로 하자~',
      timestamp: '어제 오후 8:10',
      isMyMessage: false,
      riskLevel: 'DANGER',
      riskCategory: 'GROOMING',
      aiExplanation: '⚠️ 매우 위험해요! 온라인에서 만난 사람이 직접 만나자고 하거나 "비밀로 하자"고 하면 절대로 응하면 안 돼요. 이것은 "온라인 그루밍"이라는 범죄 행위예요. 지금 바로 부모님께 이 대화를 보여주세요!',
    },
  ],
};

// 입력 시 경고할 표현들
export const WARNING_EXPRESSIONS = [
  {
    original: '바보',
    suggestion: '조금 서툴러요',
    reason: '"바보"는 상대방의 기분을 상하게 할 수 있어요.',
  },
  {
    original: '짜증나',
    suggestion: '속상해요',
    reason: '감정을 더 부드럽게 표현해볼까요?',
  },
  {
    original: '싫어',
    suggestion: '별로예요',
    reason: '조금 더 예의 바른 표현으로 바꿔볼까요?',
  },
  {
    original: '멍청',
    suggestion: '실수했어요',
    reason: '"멍청"이라는 말은 상대방에게 상처를 줄 수 있어요.',
  },
  {
    original: '꺼져',
    suggestion: '잠시 시간이 필요해요',
    reason: '"꺼져"는 매우 무례한 표현이에요.',
  },
  {
    original: '죽어',
    suggestion: '',
    reason: '⚠️ 이 표현은 사용하면 안 돼요. 누군가에게 큰 상처를 줄 수 있는 심각한 말이에요.',
  },
];
